### ISSUE TITLE
Vronk

### ISSUE THREAD

**Issue by Delthas** [linuxomaniac/IvanTheGeminator#1]
!camaradesNabes

**Comment by Delthas** [comment]
V~

**Comment by Delthas** [comment]
@linuxomaniac

**Comment by linuxomaniac** [comment]
Il est mort à cause de toi ; tu n'as pas su le protéger, tout comme tu n'as pas su me protéger moi. Tu es condamné à voir tous ceux que tu aimes mourir.

**Comment by Delthas** [comment]
HAHA yes
